# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2440446ca1982cda46f0926a651b21d7359e272e56928e9bfb0538ecfa3abd1f2a4cd7baf6a7c94775cb07ad4c1423b59b2a17e97ece8e17b47c5ae5dc25b094

test:
  secret_key_base: 2e1b46165bab61f58d32eb44c54731b526ab74fcb5c741cc829868492384f6f7945a575e8f67585a07aae843e2ef07dd7860b88cba20bc4dbdc500ebc26e55b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
